name: Test Workflow

on:
  push:
    branches: 
      - dev

jobs:
  Deploy: 
    name: Test cloning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone cloud-api-specs Repo
        uses: actions/checkout@v3
        with:
          repository: 'sbacarob/three-little-pigs'
          path: modules/glue/cloud-api-specs/

      - name: Run Python script to resolve references
        run: python modules/glue/json-schema-ref-resolver.py --paths '${{ vars.SCHEMA_PATHS }}'

      - name: Run TF
        working-directory: backend/test
        run: terraform init && terraform apply -auto-approve
        env:
          TF_VAR_glue_schema_paths: ${{ vars.SCHEMA_PATHS }}
