name: Test Workflow

on:
  push:
    branches: 
      - dev

jobs:
  Deploy: 
    name: Test cloning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone cloud-api-specs Repo
        uses: actions/checkout@v3
        with:
          repository: 'sbacarob/three-little-pigs'
          path: cloud-api-specs

      - name: Move cloud-api-specs next to script
        run: mv cloud-api-specs ../terraform-iot-analytics/modules/glue/

      - name: Run Python script to resolve references
        run: python ../terraform-iot-analytics/modules/glue/json-schema-ref-resolver.py
